name: flutter_stripe_test
description: flutter_stripe_test
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: ^2.2.0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

